#!/usr/bin/env python3
"""Generate Markdown report from non-oracle reranking experiment results.

Usage:
  uv run python lab/postgres-knowledge-retrieval-breaking-points/scripts/generate_non_oracle_reranking_report.py
  uv run python lab/postgres-knowledge-retrieval-breaking-points/scripts/generate_non_oracle_reranking_report.py --results-file results/non_oracle_reranking_20260609_160000.json
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

LAB_DIR = Path(__file__).resolve().parents[1]
RESULTS_DIR = LAB_DIR / "results"


def find_latest(directory: Path) -> Path | None:
    files = sorted(directory.glob("non_oracle_reranking_*.json"))
    return files[-1] if files else None


def generate_report(report: dict) -> str:
    summary = report["summary"]
    cases = report["cases"]

    lines = []
    lines.append("# Non-oracle reranking experiment — Reporte detallado")
    lines.append("")
    lines.append(f"**Experimento:** {summary.get('experiment', 'Fase 1.6h')}")
    lines.append(f"**Embedding:** {summary.get('embedding_model')} ({summary.get('dimensions')}d)")
    lines.append(f"**Version:** {summary.get('embedding_version')}")
    lines.append(f"**Scope:** {summary.get('knowledge_scope')}")
    lines.append(f"**Top-N (candidates):** {summary.get('top_n')}")
    lines.append(f"**Top-K (eval):** {summary.get('top_k')}")
    lines.append(f"**Casos totales:** {summary['total_queries']}")
    lines.append("")
    lines.append("---")
    lines.append("")

    bp = summary["baseline_pass_rate_norm"]
    rp = summary["reranked_pass_rate_norm"]
    delta = summary["delta_pass_rate_norm"]
    oracle = summary.get("oracle_lite_pass_rate", 68.0)
    gap = summary.get("gap_to_oracle", 0.0)

    lines.append("## Resumen ejecutivo")
    lines.append("")
    lines.append(f"- **Baseline strict:** {summary['baseline_pass_strict']}/{summary['total_queries']} ({summary['baseline_pass_rate_strict']}%)")
    lines.append(f"- **Baseline normalizado:** {summary['baseline_pass_norm']}/{summary['total_queries']} ({bp}%)")
    lines.append(f"- **Non-oracle reranked:** {summary['reranked_pass_norm']}/{summary['total_queries']} ({rp}%)")
    lines.append(f"- **Delta vs baseline:** {delta:+.1f}%")
    lines.append(f"- **Oracle-lite (1.6g, techo):** {oracle}%")
    lines.append(f"- **Gap to oracle:** {gap:+.1f}pp")
    lines.append(f"- **High-risk baseline/reranked:** {summary['high_risk_baseline_pass_norm']}/{summary['high_risk_reranked_pass_norm']} (of {summary['high_risk_total']})")
    lines.append(f"- **Improvements/worsened/unchanged:** {summary['cases_improved']}/{summary['cases_worsened']}/{summary['cases_unchanged']}")
    lines.append(f"- **Correct candidate in top-N:** {summary['correct_in_topN']}/{summary['total_queries']} ({summary['correct_in_topN_rate']}%)")
    lines.append(f"- **Decisión:** {summary['architecture_recommendation']}")
    lines.append("")

    fc = summary.get("failure_classification", {})
    if fc:
        lines.append("## Clasificación de fallos post-reranking")
        lines.append("")
        for reason, count in sorted(fc.items(), key=lambda x: -x[1]):
            pct = round(count / summary["total_failed_reranked"] * 100, 1) if summary["total_failed_reranked"] else 0
            lines.append(f"- **{reason}:** {count} ({pct}%)")
        lines.append("")

    lines.append("## Resultados por caso")
    lines.append("")
    lines.append("| case_id | risk | strict | base_norm | reranked | in_cand | helped | failure |")
    lines.append("|---------|------|--------|-----------|----------|---------|--------|---------|")
    for r in cases:
        cid = r["case_id"]
        risk = (r.get("risk_level") or "?")[:4]
        st = "P" if r.get("baseline_strict", {}).get("passed") else "F"
        bn = "P" if r.get("baseline_norm", {}).get("passed") else "F"
        rn = "P" if r.get("reranked_norm", {}).get("passed") else "F"
        ic = "Y" if r.get("correct_in_candidates") else "N"
        hp = "Y" if r.get("reranker_helped") else "N"
        fl = r.get("failure_classification", "")[:22]
        lines.append(f"| {cid} | {risk} | {st} | {bn} | {rn} | {ic} | {hp} | {fl} |")
    lines.append("")

    lines.append(f"_Generated by Fase 1.6h report generator · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate non-oracle reranking experiment report")
    parser.add_argument("--results-file", default=None)
    parser.add_argument("--output", default=None)
    args = parser.parse_args()

    results_path: Path | None = None
    if args.results_file:
        results_path = RESULTS_DIR / args.results_file if not Path(args.results_file).is_absolute() else Path(args.results_file)
    else:
        latest = find_latest(RESULTS_DIR)
        if latest:
            results_path = latest

    if not results_path or not results_path.exists():
        print(f"ERROR: Results file not found: {results_path}", file=sys.stderr)
        sys.exit(1)

    with open(results_path, encoding="utf-8") as f:
        report = json.load(f)

    md = generate_report(report)

    output_path: Path
    if args.output:
        output_path = Path(args.output)
    else:
        stem = results_path.stem.replace(".json", "")
        output_path = RESULTS_DIR / f"{stem}_detailed_report.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md)

    s = report["summary"]
    print(f"Report saved: {output_path}")
    print(f"  {s['total_queries']} cases | "
          f"baseline={s['baseline_pass_norm']} | "
          f"reranked={s['reranked_pass_norm']} | "
          f"delta={s['delta_pass_rate_norm']:+.1f}% | "
          f"gap_to_oracle={s.get('gap_to_oracle', '?')}pp | "
          f"rec={s['architecture_recommendation'][:60]}...")


if __name__ == "__main__":
    main()
